[DYCLOUD]2024-11-12 14:10:09.206	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/service/kubernetes/node/k8s_node.go:102	the server could not find the requested resource (get nodes.metrics.k8s.io)
[DYCLOUD]2024-11-12 14:10:12.296	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/service/kubernetes/workload/deployment/k8s_deployment.go:82	MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
[DYCLOUD]2024-11-12 14:11:39.993	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/service/kubernetes/node/k8s_node.go:55	Get "https://192.168.31.40:6443/api/v1/nodes": dial tcp 192.168.31.40:6443: connect: connection refused
[DYCLOUD]2024-11-12 14:11:42.963	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/api/v1/kubernetes/clusterManager/cluster/k8s_cluster.go:386	获取命名空间失败!	{"error": "Get \"https://192.168.31.40:6443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings?labelSelector=devops%2Fmanage%3Ddevops%2Cdevops%2Fcluster-id%3D5a24c167-7abc-4e00-88ae-ded3615d1d9f%2Cdevops%2Fusername%3Dadmin\": dial tcp 192.168.31.40:6443: connect: connection refused"}
[DYCLOUD]2024-11-12 14:11:44.761	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/service/kubernetes/node/k8s_node.go:55	Get "https://192.168.31.40:6443/api/v1/nodes": dial tcp 192.168.31.40:6443: connect: connection refused
[DYCLOUD]2024-11-12 14:11:45.984	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/api/v1/kubernetes/clusterManager/cluster/k8s_cluster.go:386	获取命名空间失败!	{"error": "Get \"https://192.168.31.40:6443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings?labelSelector=devops%2Fmanage%3Ddevops%2Cdevops%2Fcluster-id%3D5a24c167-7abc-4e00-88ae-ded3615d1d9f%2Cdevops%2Fusername%3Dadmin\": dial tcp 192.168.31.40:6443: connect: connection refused"}
[DYCLOUD]2024-11-12 14:11:50.337	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/service/kubernetes/namespace/k8s_namespace.go:36	获取失败:Get "https://192.168.31.40:6443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings?labelSelector=devops%2Fmanage%3Ddevops%2Cdevops%2Fcluster-id%3D5a24c167-7abc-4e00-88ae-ded3615d1d9f%2Cdevops%2Fusername%3Dadmin": dial tcp 192.168.31.40:6443: connect: connection refused
[DYCLOUD]2024-11-12 14:11:50.339	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/api/v1/kubernetes/namespaceManager/namespaces/k8s_namespaces.go:28	获取失败!	{"error": "Get \"https://192.168.31.40:6443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings?labelSelector=devops%2Fmanage%3Ddevops%2Cdevops%2Fcluster-id%3D5a24c167-7abc-4e00-88ae-ded3615d1d9f%2Cdevops%2Fusername%3Dadmin\": dial tcp 192.168.31.40:6443: connect: connection refused"}
[DYCLOUD]2024-11-12 14:12:03.702	[31merror[0m	/Users/dujie/Desktop/cmdb/持续更新/cmdb/server/api/v1/kubernetes/clusterManager/cluster/k8s_cluster.go:386	获取命名空间失败!	{"error": "Get \"https://192.168.31.40:6443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings?labelSelector=devops%2Fmanage%3Ddevops%2Cdevops%2Fcluster-id%3D5a24c167-7abc-4e00-88ae-ded3615d1d9f%2Cdevops%2Fusername%3Dadmin\": dial tcp 192.168.31.40:6443: connect: connection refused"}
